"=============================
"== .vimrc for general use  ==
"== author: Sam Ebertz      ==
"=============================

"=============================
"== Pathogen plugin manager ==
"=============================
call pathogen#incubate()
call pathogen#helptags()

set ai
set si
set wrap
syntax on
