"=============================
"== .vimrc for general use  ==
"== author: Sam Ebertz      ==
"=============================

"=============================
"== Vim default settings    ==
"=============================
set ai
set si
set wrap
syntax on

"=============================
"== Pathogen plugin manager ==
"=============================
call pathogen#incubate()
call pathogen#helptags()

"=============================
"== CommandT file opener    ==
"=============================
"noremap <leader>o <Esc>:CommandT<CR>
"noremap <leader>O <Esc>:CommandTFlush<CR>
"noremap <leader>m <Esc>:CommandTBuffer<CR>

"=============================
"== CloseTag                ==
"=============================
autocmd FileType html,htmldjango,jinjahtml,eruby,mako let b:closetag_html_style=1
autocmd FileType html,xhtml,xml,htmldjango,jinjahtml,eruby,mako source ~/.vim/bundle/closetag/plugin/closetag.vim

"=============================
"== Tagbar tag browsing     ==
"=============================
"let g:tagbar_usearrows=1
"noremap <leader>l <Esc>:TagbarToggle<Cr>

"=============================
"== Solarized color scheme  ==
"==                         ==
"== !! NEEDS 256 COLOR TERM ==
"=============================
"set background=dark
"let g:solarized_termtrans=1
"let g:solarized_termcolors=256
"let g:solarized_contrast="high"
"let g:solarized_visibility="high"
"colorscheme solarized

"=============================
"== Molokai color scheme    ==
"==                         ==
"== !! NEEDS 256 COLOR TERM ==
"=============================
"g:rehash256=1
"colorscheme molokai
"set background=dark

"=============================
"== "
